# NumPy Basics: Arrays and Vectorized Computation

In [7]:
%matplotlib inline

ModuleNotFoundError: No module named 'matplotlib'

In [8]:
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

## The NumPy ndarray: a multidimensional array object

In [11]:

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

#from IPython.core

In [15]:
data = randn(2, 3)      # 랜덤 값으로 배열 형성함.

In [16]:
print(data)

[[-1.5119 -0.3879 -0.1754]
 [ 0.9761 -0.0925 -0.6811]]


In [17]:
print(data * 10)           #10이 다 영향을 끼치게 됨. broadcasting

[[-15.1187  -3.8786  -1.7543]
 [  9.7607  -0.9248  -6.8114]]


In [18]:
print(data + data)   # 2,3  2,3

[[-3.0237 -0.7757 -0.3509]
 [ 1.9521 -0.185  -1.3623]]


In [20]:
type(data)   # 넘파이 패키지의 ndarray 클래스 객체이다.

numpy.ndarray

In [19]:
print(data.shape)   # 차원의 크기 2행 3열
print(data.dtype)   # 데이터 형은 실수형

(2, 3)
float64


### Creating ndarrays

In [55]:
from IPython.core.interactiveshell import InteractiveShell

In [56]:
InteractiveShell.ast_node_interactivity = 'all'

In [57]:
data1 = [6, 7.5, 8, 0, 1]   # 리스트 형성
arr1 = np.array(data1)      # np.array 메소드를 만들어서 data1을 넣어줌.
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [58]:
print(arr1)  # 겉으로 봐서 리스트로 보이나, 다르다. 아래 type을 쳐봐야함.

[6.  7.5 8.  0.  1. ]


In [59]:
type(arr1) 

numpy.ndarray

In [60]:
arr1?
np.array?

In [61]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]  # 첫번째 원소 : 4개짜리 리스트  / 
arr2 = np.array(data2)                
print(arr2)                       # 2차원의 리스트
print(arr2.ndim)          # 몇 차원의 배열이냐?
print(arr2.shape)        # 2차원행렬에서 행과 열의 크기가 어떻게 되는가??

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [62]:
arr1.dtype

dtype('float64')

In [63]:
arr2.dtype

dtype('int32')

In [64]:
np.zeros(10)    # 0 행렬을 만들어달라. 1차원배열 / 원소가 10개

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
type(np.zeros(10))

numpy.ndarray

In [66]:
np.zeros_like(arr2) 

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [67]:
np.ones_like(arr2) # 모든 원소가 1인 

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [68]:
np.zeros((3, 6)) 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [69]:
np.empty((2, 3, 2))   # 가비지 값으로 119p / empty = 데이터 값이 0이 아니라, 아무 값이나 채워서 보냄.

array([[[1.5221e-311, 2.4703e-322],
        [0.0000e+000, 0.0000e+000],
        [0.0000e+000, 6.8212e-043]],

       [[7.7390e-091, 4.5024e+174],
        [2.3269e-057, 7.3153e+169],
        [3.9991e+252, 1.6193e-051]]])

In [70]:
np.arange(15)  # arange 잘 쓰여짐. 1차원 array 반환.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [71]:
np.arange(20, step=3)   # 옵션 = step 3칸씩 띄워서

array([ 0,  3,  6,  9, 12, 15, 18])

In [72]:
np.arange(20, step=3, dtype=np.float32)   # np.float32  다 써주어야함.

array([ 0.,  3.,  6.,  9., 12., 15., 18.], dtype=float32)

In [73]:
np.eye(3)     # eye identity 단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
x = np.empty((4, 4))     # empty 행렬을 만들어서 x에 넣었다.
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [75]:
np.identity(x.shape[0])    # x와 똑같은 단위행렬을 만드는 것

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Data Types for ndarrays

In [76]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype

dtype('float64')

dtype('int32')

In [79]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)      #astype 메서드 ndarray.astype(dtype [, order, casting, ...])	 `지정된 형식으로 캐스트 된 배열의 복사본입니다.
float_arr.dtype

dtype('int32')

dtype('float64')

In [80]:
print(arr.dtype, float_arr.dtype)   # 타입을 변환한 후에 결과값을 리턴함.

int32 float64


In [81]:
print(arr, float_arr)

[1 2 3 4 5] [1. 2. 3. 4. 5.]


In [83]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr # 1차원 넘파이 객체 생성

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [86]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [87]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [89]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)  # 얘는 문자열이야!
numeric_strings.astype(float)      # 파이썬의 플로트 함수

array([ 1.25, -9.6 , 42.  ])

In [91]:
int_array = np.arange(10)   # np.arange   0~9까지 만들어줌
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)  #int_array 를 calibers.dtype와 같은 타입으로 바꾸겠다.

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [103]:
empty_uint32 = np.empty(8, dtype='u4')   # 8개짜리 1차원 배열 / u4 = 32비트 / empty - 아무 값이나 들어옴.
empty_uint32 

array([         0,          0, 1805908096,          0,          2,
                0, 4294967295, 4294967295], dtype=uint32)

### Operations between arrays and scalars

In [104]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [105]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [106]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [107]:
1 / arr      # np.ones_like(arr) / arr 과 같으나 1/arr이 더 쉬움.

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [109]:
np.ones_like(arr)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [110]:
np.ones_like(arr) / arr

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [111]:
arr ** 0.5 #제곱근

array([[1.    , 1.4142, 1.7321],
       [2.    , 2.2361, 2.4495]])

In [112]:
arr.shape  # 몇 행 몇 열

(2, 3)

### Basic indexing and slicing

In [113]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

5

array([5, 6, 7])

In [119]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [118]:
# 파이썬 리스트인 경우
l = list(range(10))
l
l[5:8] = 12  # 슬라이싱은 값이 바꿀 때 에러가 남.       => 넘파이 배열은 가능하다.
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

TypeError: can only assign an iterable

In [120]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [121]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [122]:
# 넘파이는 다량의 데이터 처리를 염두에 두고 개발되었기 때문에 배열의 슬라이스는
# 원본의 참조를 리턴한다. 따라서 슬라이스의 원소를 변경하면 원본에도 영향을 미친다.
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [123]:
p_list = [1, 2, 3, 4, 5]
p = p_list[2:4]
p

[3, 4]

In [124]:
p[0] = 300
p

[300, 4]

In [125]:
p_list

[1, 2, 3, 4, 5]

In [126]:
arr_slice[:] = 64
arr_slice

array([64, 64, 64])

In [127]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [130]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # [[ 2개니까 2차원 배열]]
arr2d
arr2d[2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([7, 8, 9])

In [133]:
arr2d[0][2] #   0,2  /  0행, 2열

3

In [134]:
arr2d[0, 2]

3

In [136]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  #]]] 3차원 배열 - 2차원이 쌓여있는 것
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [138]:
print(arr3d.ndim, arr3d.shape)  # 차원 = 3차원 / 형태 = 223 -> 1차원 = 3열, 2차원 2행, 3차원 2

3 (2, 2, 3)


In [145]:
#1차원 배열
a1 = np.array([1,2,3])
a1
a1.ndim, a1.shape # 1차원 . 컬럼이 3개다.

#2차원 배열
a2 = np.array([[1,2,3],[4,5,6]])
a2
a2.ndim, a2.shape # 2차원 . 2,3   추가된 행이 앞쪽에 붙음

#
a21 = np.array([[1,2,3]])
a21
a21.ndim, a21.shape        # 2차원 / 

#3차원 배열
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
a3
a3.ndim, a3.shape          # 3차원, 2, 2, 3행

array([1, 2, 3])

(1, (3,))

array([[1, 2, 3],
       [4, 5, 6]])

(2, (2, 3))

array([[1, 2, 3]])

(2, (1, 3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

(3, (2, 2, 3))

In [147]:
arr3d[0]    # 첫번째 

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
old_values = arr3d[0].copy() # 값은 돌아오는 거야
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [149]:
arr3d[0] = old_values      # 값은 돌아오는 거야
arr3d  

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [150]:
arr3d[1, 0]      # 차원 단위 1 / 그 차원에서 0번째-  데이터 컬럼, 로우, 축

array([7, 8, 9])

#### Indexing with slices

In [151]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [152]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
arr2d.shape[1]

3

In [154]:
arr2d
arr2d[:2]     # 2번째 점까지 - row    / 3차원이면 지축, 로우, 열   / 2차원 열, 로우  / 1차원 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [156]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [157]:
arr2d[1, :2]
arr2d[2, :1]

array([4, 5])

array([7])

In [158]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [ ]:
arr2d[:2, 1:] = 0
arr2d

### Boolean indexing

In [159]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names.shape)    # 튜플 - ( 7, )
names

(7,)


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [160]:
data = np.random.randn(7, 4)   # 7행 4열의 값을 넣어줌   
names
data

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

array([[-1.2571,  0.3556, -1.4373, -1.5079],
       [ 0.8089, -0.6071, -0.2925, -0.1864],
       [ 0.0467,  0.0219, -1.7132, -0.0112],
       [ 1.5697, -0.0725, -0.9869, -0.5582],
       [-0.2989, -1.674 , -0.71  ,  0.2454],
       [ 1.212 ,  0.1045,  1.5086,  0.0343],
       [-0.2934,  0.305 ,  0.861 ,  1.1381]])

In [161]:
names == 'Bob'  #names 의 값과 비교한다고 생각하면 됨.        

array([ True, False, False,  True, False, False, False])

In [162]:
data[names == 'Bob']   # []d 안에 TFTF  들어옴. 첫번째행 2번째행 매칭이 됨 => True 인 2개의 행이 선택이 됨.   불리언 인덱싱

array([[-1.2571,  0.3556, -1.4373, -1.5079],
       [ 1.5697, -0.0725, -0.9869, -0.5582]])

In [163]:
data[names == 'Bob', 2:]    # 2부터 끝까지~~~

array([[-1.4373, -1.5079],
       [-0.9869, -0.5582]])

In [165]:
data[names == 'Bob', 3]     # 3번째 컬럼 값이 나옴 / 하나를 지정했기 때문에 차원이 2차원에서 1차원으로 줄어듬.

array([-1.5079, -0.5582])

In [166]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [167]:
~(names == 'Bob')   # ~ 틸드  tilde

array([False,  True,  True, False,  True,  True,  True])

In [168]:
data[~(names == 'Bob')]

array([[ 0.8089, -0.6071, -0.2925, -0.1864],
       [ 0.0467,  0.0219, -1.7132, -0.0112],
       [-0.2989, -1.674 , -0.71  ,  0.2454],
       [ 1.212 ,  0.1045,  1.5086,  0.0343],
       [-0.2934,  0.305 ,  0.861 ,  1.1381]])

In [169]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [170]:
names == 'Will'

array([False, False,  True, False,  True, False, False])

In [171]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [172]:
mask
data[mask]

array([ True, False,  True,  True,  True, False, False])

array([[-1.2571,  0.3556, -1.4373, -1.5079],
       [ 0.0467,  0.0219, -1.7132, -0.0112],
       [ 1.5697, -0.0725, -0.9869, -0.5582],
       [-0.2989, -1.674 , -0.71  ,  0.2454]])

In [173]:
data

array([[-1.2571,  0.3556, -1.4373, -1.5079],
       [ 0.8089, -0.6071, -0.2925, -0.1864],
       [ 0.0467,  0.0219, -1.7132, -0.0112],
       [ 1.5697, -0.0725, -0.9869, -0.5582],
       [-0.2989, -1.674 , -0.71  ,  0.2454],
       [ 1.212 ,  0.1045,  1.5086,  0.0343],
       [-0.2934,  0.305 ,  0.861 ,  1.1381]])

In [174]:
data < 0      # 전체 data에 대해서  T F 판단

array([[ True, False,  True,  True],
       [False,  True,  True,  True],
       [False, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [175]:
data[data < 0]       # 이 결과를 자기 자신에게 0보다 작은 값만 보고 싶다면  1차원 데이터로 나타나게 된다.

array([-1.2571, -1.4373, -1.5079, -0.6071, -0.2925, -0.1864, -1.7132,
       -0.0112, -0.0725, -0.9869, -0.5582, -0.2989, -1.674 , -0.71  ,
       -0.2934])

In [176]:
data[data < 0] = 0   # 0으로 값을 바꾸겠다.  리사이클룰 적용됨.
data

array([[0.    , 0.3556, 0.    , 0.    ],
       [0.8089, 0.    , 0.    , 0.    ],
       [0.0467, 0.0219, 0.    , 0.    ],
       [1.5697, 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.2454],
       [1.212 , 0.1045, 1.5086, 0.0343],
       [0.    , 0.305 , 0.861 , 1.1381]])

In [180]:
names[names != 'Joe']=True
names

array(['True', 'Joe', 'True', 'True', 'True', 'Joe', 'Joe'], dtype='<U4')

In [181]:
data[names != 'Joe'] = 7   # 1,3,4,5, 이 7로 바뀜.
data

array([[7.    , 7.    , 7.    , 7.    ],
       [0.8089, 0.    , 0.    , 0.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [1.212 , 0.1045, 1.5086, 0.0343],
       [0.    , 0.305 , 0.861 , 1.1381]])

### Fancy indexing

In [200]:
arr = np.empty((8, 4))   # 8행 4열
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [201]:
for i in range(arr.shape[0]):
    arr[i] = i               # 초기화 한번 해줌.
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [203]:
arr[[4, 3, 0, 6]]        # 4,3,0,6 번째 인덱스 순서대로 뽑겠다.   [[ 팬시 색인 ]] // 슬라이싱 : 

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [205]:
arr[[-3, -5, -7]]    # 8개 -3 / 8개 -5 -7   5 3 1번쨰 인덱스 순서대로 뽑겠다.

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [207]:
np.arange(32).reshape(8, 4)   # reshape        다시 형태(형상)을 지정하겠다. 
# np 모듈의 arrange 메소드의 reshape의 메소드
# 파이썬은 기본적으로 행을 먼저 채움

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [210]:
# more on reshape in Chapter 12    -- 고급 넘파이 
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [211]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]   # 팬시 색인 : 로우, 컬럼에 대해 좌표값이 됨. 4개가 나옴.

array([ 4, 23, 29, 10])

In [213]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]   # : 을 통해 0312 순으로 재배치 해라.

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [214]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]   # np.ix_   ix = index라는 뜻 /     : 대신에 np.ix_를 씀.

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [215]:
ar = np.arange(8)
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [216]:
ar.shape[0]

8

In [217]:
ar[3:7]

array([3, 4, 5, 6])

In [218]:
ar[[3, 5, 2, 1]]

array([3, 5, 2, 1])

In [219]:
ar2 = ar.reshape(2, 4)  # 1차원 배열 8개 자료를 2차원으로 바꿔줌
ar2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [220]:
ar2.shape

(2, 4)

In [221]:
ar2[1]

array([4, 5, 6, 7])

In [227]:
ar2[1:]
ar2[:1]
ar2[:,1]  # 좌표 지정

array([[4, 5, 6, 7]])

array([[0, 1, 2, 3]])

array([1, 5])

In [228]:
ar3 = np.arange(60).reshape(3, 5, 4)     # 3지축, 5행, 4열
ar3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [229]:
ar3[[1, 2], [4, 2], [0, 1]]    # 팬시색인 1,4,0 / 2,2,1   값 2개   / 차원에 맞게끔 값을 넣어주면

array([36, 49])

In [232]:
ar3[np.ix_([1, 2], [4, 2], [0, 1])]    # 범위가 되어버림.

# ar3[np.ix_([[1, 2],[:, [4, 2],[:, [0, 1]]]])]    # 범위가 되어버림.

# arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]   # : 을 통해 0312 순으로 재배치 해라.

SyntaxError: invalid syntax (<ipython-input-232-8517b3ac1452>, line 2)

In [235]:
arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [236]:
arr.shape # 1차원 배열이다.

(60,)

In [237]:
arr = arr.reshape((60, 1))
arr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59]])

### Transposing arrays and swapping axes    
####배열 전치와 축 바꾸기

In [238]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [239]:
arr.T  # 행과 열을 서로 바꿔줌.

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [241]:
arr = np.random.randn(6, 3)    # 행렬의 dot...
np.dot(arr.T, arr)             # 행렬곱셈    

array([[15.901 ,  0.2062,  1.6445],
       [ 0.2062,  6.675 , -1.5874],
       [ 1.6445, -1.5874,  5.0587]])

In [242]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [243]:
arr.shape

(2, 2, 4)

In [244]:
arr.transpose((1, 2, 0))   # 2차원일때 
arr.transpose((1, 2, 0)).shape

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

(2, 4, 2)

In [247]:
arr = np.arange(16).reshape((2, 2, 4))
arr
arr.swapaxes(1, 2)   # 1번째 축과 2번째 축을 맞바꾸는

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions: Fast element-wise array functions

In [248]:
np.sqrt(36)

6.0

In [250]:
arr = np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0.    , 1.    , 1.4142, 1.7321, 2.    , 2.2361, 2.4495, 2.6458,
       2.8284, 3.    ])

array([   1.    ,    2.7183,    7.3891,   20.0855,   54.5982,  148.4132,
        403.4288, 1096.6332, 2980.958 , 8103.0839])

In [252]:
#유니버셜 함수가 아니라면,
np.array([np.sqrt(x) for x in arr])
np.array(np.sqrt(x) for x in arr)    # 유니버셜 형태가 훨씬 간단함.

array([0.    , 1.    , 1.4142, 1.7321, 2.    , 2.2361, 2.4495, 2.6458,
       2.8284, 3.    ])

array(<generator object <genexpr> at 0x000002CD50F5F200>, dtype=object)

In [253]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)
np.maximum(x, y) # element-wise maximum    # np.maximum - 유니버셜 함수 /  알아서 8번 처리해줌.


[ 1.1913 -0.4679 -1.2975 -0.5318 -1.6671  0.6121 -1.6121 -0.4743]
[-2.8026 -0.6561 -0.5082  1.3376 -1.1391 -0.8114  0.3798  0.4115]


array([ 1.1913, -0.4679, -0.5082,  1.3376, -1.1391,  0.6121,  0.3798,
        0.4115])

In [255]:
arr = randn(7) * 5
arr
np.modf(arr)   # 실수를 소수점 이하(fractional part)와 정수부(integral part)로 분리

array([-3.3101,  0.6253,  5.4436, -8.7353, -1.7784,  0.0853, -2.0659])

(array([-0.3101,  0.6253,  0.4436, -0.7353, -0.7784,  0.0853, -0.0659]),
 array([-3.,  0.,  5., -8., -1.,  0., -2.]))

## Data processing using arrays

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
points

In [ ]:
len(points)

In [ ]:
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
xs.shape

In [ ]:
xs

In [ ]:
type(xs)

In [ ]:
from matplotlib.pyplot import imshow, title

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

In [ ]:
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")
plt.draw()

### Expressing conditional logic as array operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
list(zip([1, 2, 3], [4, 5, 6], [True, False, True]))

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = randn(4, 4)
arr

In [ ]:
np.where(arr > 0, 2, -2)

In [ ]:
arr[arr > 0] = 2
arr[arr < 0] = -2
arr

In [ ]:
np.where(arr > 0, 2, arr) # set only positive values to 2

In [ ]:
# Not to be executed

np.where(cond1 & cond2, 0,
         np.where(cond1, 1,
                  np.where(cond2, 2, 3)))

In [ ]:
1 == True

In [ ]:
# Not to be executed

result = 0 * (cond1 & cond2) + 1 * (cond1 & ~cond2)
       + 2 * (~cond1 & cond2) + 3 * (~cond1 & ~cond2)

### Mathematical and statistical methods

In [ ]:
arr = np.random.randn(5, 4) # normally-distributed data
arr

In [ ]:
print(arr.mean())
print(np.mean(arr))

In [ ]:
arr.sum()

In [ ]:
arr.mean(axis=1)

In [ ]:
arr.sum(0)

In [ ]:
arr.max(axis=1)

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]]); arr

In [ ]:
arr.cumsum(0)

In [ ]:
arr.cumprod(1)

In [ ]:
arr = np.random.randint(0, 10, (3, 3)); arr

In [ ]:
arr.argmax(0)

In [ ]:
arr.argmax(1)

### Methods for boolean arrays

In [ ]:
arr = randn(100)
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()

In [ ]:
bools.all()

In [ ]:
a = np.random.randint(0, 10, size=10); a

In [ ]:
a.any()

In [ ]:
a.all()

### Sorting

In [ ]:
arr = randn(8)
arr

In [ ]:
arr.sort()
arr

In [ ]:
arr = randn(5, 3)
arr

In [ ]:
arr.sort(0)
arr

In [ ]:
large_arr = randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

### Unique and other set logic

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

In [ ]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [ ]:
sorted(set(names))

In [ ]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

## File input and output with arrays

### Storing arrays on disk in binary format

In [ ]:
arr = np.arange(10)
np.save('some_array', arr)

In [ ]:
np.load('some_array.npy')

In [ ]:
np.savez('array_archive.npz', a=arr, b=arr)

In [ ]:
arch = np.load('array_archive.npz')
arch['b']

In [ ]:
!rm some_array.npy
!rm array_archive.npz

### Saving and loading text files

In [ ]:
!cat array_ex.txt

In [ ]:
arr = np.loadtxt('array_ex.txt', delimiter=',')
arr

## Linear algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)
x.dot(y)  # equivalently np.dot(x, y)

In [ ]:
np.dot(x, y)

In [ ]:
np.dot(x, np.ones(3))

In [ ]:
np.dot(np.ones(2), x)

In [ ]:
np.random.seed(12345)

In [ ]:
from numpy.linalg import inv, qr
X = randn(5, 5)
mat = X.T.dot(X)
inv(mat)
mat.dot(inv(mat))
q, r = qr(mat)
r

In [ ]:
X

In [ ]:
mat = X.T.dot(X); mat

In [ ]:
inv(mat)

In [ ]:
mat.dot(inv(mat))

In [ ]:
q, r = qr(mat)
r

## Random number generation

In [ ]:
samples = np.random.normal(size=(4, 4))
samples

In [ ]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.normal(size=N)

## Example: Random Walks

In [ ]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)
    
plt.plot(walk[:100])

In [ ]:
walk[:20]

In [ ]:
import random

steps = 1000
s1 = [1 if random.randint(0, 1) else -1 for _ in range(steps)]
walk = [sum(s1[:x]) for x in range(len(s1)+1)]
walk[:20]

In [ ]:
plt.plot(walk[:100])

In [ ]:
np.random.seed(12345)

In [ ]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = np.r_[[0], steps.cumsum()]

In [ ]:
walk.min()

In [ ]:
walk.max()

In [ ]:
(np.abs(walk) >= 10).argmax()

In [ ]:
walk[38]

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(walk[:100])

### Simulating many random walks at once

In [ ]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1)
walks = np.hstack((np.zeros((nwalks, 1), dtype=np.int32), walks))

In [ ]:
walks.max()

In [ ]:
walks.min()

In [ ]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30

In [ ]:
hits30.sum() # Number that hit 30 or -30

In [ ]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.mean()

In [ ]:
steps = np.random.normal(loc=0, scale=0.25,
                         size=(nwalks, nsteps))

In [ ]:
walks[hits30][:,10]

In [ ]:
(np.abs(walk) >= 10)